export const Languages: Indexable[] = [
  {
    label: '1C Enterprise',
    value: '1c',
    ext: ['1c', 'v8c'],
    icon: 'code_blocks',
  },
  {
    label: 'ABNF',
    value: 'abnf',
    ext: ['abnf'],
    icon: 'code_blocks',
  },
  {
    label: 'Access Log',
    value: 'accesslog',
    ext: ['log'],
    icon: 'code_blocks',
  },
  {
    label: 'ActionScript',
    value: 'actionscript',
    ext: ['as'],
    icon: 'code_blocks',
  },
  {
    label: 'Ada',
    value: 'ada',
    ext: ['adb', 'ads', 'ada'],
    icon: 'code_blocks',
  },
  {
    label: 'AngelScript',
    value: 'angelscript',
    ext: ['as', 'asc'],
    icon: 'code_blocks',
  },
  {
    label: 'Apache Config',
    value: 'apache',
    ext: ['conf', 'htaccess'],
    icon: 'code_blocks',
  },
  {
    label: 'AppleScript',
    value: 'applescript',
    ext: ['scpt', 'applescript'],
    icon: 'code_blocks',
  },
  {
    label: 'Arcade',
    value: 'arcade',
    ext: ['arcade'],
    icon: 'code_blocks',
  },
  {
    label: 'Arduino',
    value: 'arduino',
    ext: ['ino', 'pde'],
    icon: 'code_blocks',
  },
  {
    label: 'ARM Assembly',
    value: 'armasm',
    ext: ['s', 'asm'],
    icon: 'code_blocks',
  },
  {
    label: 'AsciiDoc',
    value: 'asciidoc',
    ext: ['adoc', 'asciidoc'],
    icon: 'code_blocks',
  },
  {
    label: 'AspectJ',
    value: 'aspectj',
    ext: ['aj'],
    icon: 'code_blocks',
  },
  {
    label: 'AutoHotkey',
    value: 'autohotkey',
    ext: ['ahk'],
    icon: 'code_blocks',
  },
  {
    label: 'AutoIt',
    value: 'autoit',
    ext: ['au3'],
    icon: 'code_blocks',
  },
  {
    label: 'AVR Assembly',
    value: 'avrasm',
    ext: ['s', 'asm'],
    icon: 'code_blocks',
  },
  {
    label: 'AWK',
    value: 'awk',
    ext: ['awk', 'gawk', 'mawk', ' nawk'],
    icon: 'code_blocks',
  },
  {
    label: 'Axapta',
    value: 'axapta',
    ext: ['xpo', 'axp'],
    icon: 'code_blocks',
  },
  {
    label: 'BASIC',
    value: 'basic',
    ext: ['bas'],
    icon: 'code_blocks',
  },
  {
    label: 'Bash',
    value: 'bash',
    ext: ['sh', 'bash', 'zsh'],
    icon: 'code_blocks',
  },
  {
    label: 'BNF',
    value: 'bnf',
    ext: ['bnf'],
    icon: 'code_blocks',
  },
  {
    label: 'Brainfuck',
    value: 'brainfuck',
    ext: ['bf', 'b'],
    icon: 'code_blocks',
  },
  {
    label: 'CAL',
    value: 'cal',
    ext: ['cal'],
    icon: 'code_blocks',
  },
  {
    label: 'Capn Proto',
    value: 'capnproto',
    ext: ['capnp'],
    icon: 'code_blocks',
  },
  {
    label: 'Ceylon',
    value: 'ceylon',
    ext: ['ceylon'],
    icon: 'code_blocks',
  },
  {
    label: 'Clean',
    value: 'clean',
    ext: ['icl', 'dcl', 'prg'],
    icon: 'code_blocks',
  },
  {
    label: 'Clojure',
    value: 'clojure',
    ext: ['clj', 'cljs', 'cljc'],
    icon: 'code_blocks',
  },
  {
    label: 'Clojure REPL',
    value: 'clojure-repl',
    ext: ['clj'],
    icon: 'code_blocks',
  },
  {
    label: 'CMake',
    value: 'cmake',
    ext: ['cmake', 'CMakeLists.txt'],
    icon: 'code_blocks',
  },
  {
    label: 'CoffeeScript',
    value: 'coffeescript',
    ext: ['coffee', 'litcoffee'],
    icon: 'code_blocks',
  },
  {
    label: 'Coq',
    value: 'coq',
    ext: ['v'],
    icon: 'code_blocks',
  },
  {
    label: 'COS',
    value: 'cos',
    ext: ['cos'],
    icon: 'code_blocks',
  },
  {
    label: 'C++',
    value: 'cpp',
    ext: ['cpp', 'hpp', 'cc', 'cxx', 'h', 'hxx'],
    icon: 'code_blocks',
  },
  {
    label: 'crmsh',
    value: 'crmsh',
    ext: ['crm', 'pcs'],
    icon: 'code_blocks',
  },
  {
    label: 'Crystal',
    value: 'crystal',
    ext: ['cr'],
    icon: 'code_blocks',
  },
  {
    label: 'C#',
    value: 'csharp',
    ext: ['cs'],
    icon: 'code_blocks',
  },
  {
    label: 'CSP',
    value: 'csp',
    ext: ['csp'],
    icon: 'code_blocks',
  },
  {
    label: 'CSS',
    value: 'css',
    ext: ['css'],
    icon: 'code_blocks',
  },
  {
    label: 'C',
    value: 'c',
    ext: ['c', 'h'],
    icon: 'code_blocks',
  },
  {
    label: 'D',
    value: 'd',
    ext: ['d', 'di'],
    icon: 'code_blocks',
  },
  {
    label: 'Dart',
    value: 'dart',
    ext: ['dart'],
    icon: 'code_blocks',
  },
  {
    label: 'Delphi',
    value: 'delphi',
    ext: ['pas', 'dfm', 'dpr', 'dpk'],
    icon: 'code_blocks',
  },
  {
    label: 'Diff',
    value: 'diff',
    ext: ['diff', 'patch'],
    icon: 'code_blocks',
  },
  {
    label: 'Django',
    value: 'django',
    ext: ['html', 'py', 'css', 'js'],
    icon: 'code_blocks',
  },
  {
    label: 'DNS Zone File',
    value: 'dns',
    ext: ['zone', 'dns'],
    icon: 'code_blocks',
  },
  {
    label: 'Dockerfile',
    value: 'dockerfile',
    ext: ['Dockerfile', 'dockerfile'],
    icon: 'code_blocks',
  },
  {
    label: 'DOS Batch',
    value: 'dos',
    ext: ['bat', 'cmd'],
    icon: 'code_blocks',
  },
  {
    label: 'dsconfig',
    value: 'dsconfig',
    ext: ['dsconfig'],
    icon: 'code_blocks',
  },
  {
    label: 'DTS',
    value: 'dts',
    ext: ['dts', 'dtsi'],
    icon: 'code_blocks',
  },
  {
    label: 'Dust',
    value: 'dust',
    ext: ['dust', 'dst'],
    icon: 'code_blocks',
  },
  {
    label: 'EBNF',
    value: 'ebnf',
    ext: ['ebnf'],
    icon: 'code_blocks',
  },
  {
    label: 'Elixir',
    value: 'elixir',
    ext: ['ex', 'exs'],
    icon: 'code_blocks',
  },
  {
    label: 'Elm',
    value: 'elm',
    ext: ['elm'],
    icon: 'code_blocks',
  },
  {
    label: 'ERB',
    value: 'erb',
    ext: ['erb', 'rhtml'],
    icon: 'code_blocks',
  },
  {
    label: 'Erlang',
    value: 'erlang',
    ext: ['erl', 'hrl'],
    icon: 'code_blocks',
  },
  {
    label: 'Erlang REPL',
    value: 'erlang-repl',
    ext: ['erl'],
    icon: 'code_blocks',
  },
  {
    label: 'Excel',
    value: 'excel',
    ext: ['xls', 'xlsx'],
    icon: 'code_blocks',
  },
  {
    label: 'FIX',
    value: 'fix',
    ext: ['fix'],
    icon: 'code_blocks',
  },
  {
    label: 'Flix',
    value: 'flix',
    ext: ['flix'],
    icon: 'code_blocks',
  },
  {
    label: 'Fortran',
    value: 'fortran',
    ext: ['f', 'for', 'f90', 'f95', 'f03', 'f08'],
    icon: 'code_blocks',
  },
  {
    label: 'F#',
    value: 'fsharp',
    ext: ['fs', 'fsi', 'fsx'],
    icon: 'code_blocks',
  },
  {
    label: 'GAMS',
    value: 'gams',
    ext: ['gms', 'gams'],
    icon: 'code_blocks',
  },
  {
    label: 'Gauss',
    value: 'gauss',
    ext: ['gss', 'prg'],
    icon: 'code_blocks',
  },
  {
    label: 'G-code',
    value: 'gcode',
    ext: ['nc', 'gcode', 'g', 'ngc'],
    icon: 'code_blocks',
  },
  {
    label: 'Gherkin',
    value: 'gherkin',
    ext: ['feature'],
    icon: 'code_blocks',
  },
  {
    label: 'GLSL',
    value: 'glsl',
    ext: ['vert', 'frag', 'geom', 'comp', 'tesc', 'tese', 'glsl'],
    icon: 'code_blocks',
  },
  {
    label: 'GameMaker Language',
    value: 'gml',
    ext: ['gml', 'gm81', 'gm'],
    icon: 'code_blocks',
  },
  {
    label: 'Golo',
    value: 'golo',
    ext: ['golo'],
    icon: 'code_blocks',
  },
  {
    label: 'Go',
    value: 'go',
    ext: ['go'],
    icon: 'code_blocks',
  },
  {
    label: 'Gradle',
    value: 'gradle',
    ext: ['gradle', 'gradle.kts'],
    icon: 'code_blocks',
  },
  {
    label: 'GraphQL',
    value: 'graphql',
    ext: ['graphql', 'gql'],
    icon: 'code_blocks',
  },
  {
    label: 'Groovy',
    value: 'groovy',
    ext: ['groovy', 'gvy', 'gy', 'gsh'],
    icon: 'code_blocks',
  },
  {
    label: 'Haml',
    value: 'haml',
    ext: ['haml'],
    icon: 'code_blocks',
  },
  {
    label: 'Handlebars',
    value: 'handlebars',
    ext: ['hbs', 'handlebars', 'html'],
    icon: 'code_blocks',
  },
  {
    label: 'Haskell',
    value: 'haskell',
    ext: ['hs', 'lhs'],
    icon: 'code_blocks',
  },
  {
    label: 'Haxe',
    value: 'haxe',
    ext: ['hx'],
    icon: 'code_blocks',
  },
  {
    label: 'HSP',
    value: 'hsp',
    ext: ['hsp'],
    icon: 'code_blocks',
  },
  {
    label: 'HTML',
    value: 'html',
    ext: ['html'],
    icon: 'code_blocks',
  },
  {
    label: 'HTTP',
    value: 'http',
    ext: ['http', 'rest'],
    icon: 'code_blocks',
  },
  {
    label: 'Hy',
    value: 'hy',
    ext: ['hy'],
    icon: 'code_blocks',
  },
  {
    label: 'Inform 7',
    value: 'inform7',
    ext: ['ni', 'i7x'],
    icon: 'code_blocks',
  },
  {
    label: 'INI',
    value: 'ini',
    ext: ['ini', 'cfg', 'conf'],
    icon: 'code_blocks',
  },
  {
    label: 'IRPF90',
    value: 'irpf90',
    ext: ['90', 'f90', 'f95', 'f03', 'f08'],
    icon: 'code_blocks',
  },
  {
    label: 'ISBL',
    value: 'isbl',
    ext: ['isbl'],
    icon: 'code_blocks',
  },
  {
    label: 'Java',
    value: 'java',
    ext: ['java'],
    icon: 'code_blocks',
  },
  {
    label: 'JavaScript',
    value: 'javascript',
    ext: ['js', 'jsx'],
    icon: 'code_blocks',
  },
  {
    label: 'JBoss CLI',
    value: 'jboss-cli',
    ext: ['cli'],
    icon: 'code_blocks',
  },
  {
    label: 'Julia',
    value: 'julia',
    ext: ['jl'],
    icon: 'code_blocks',
  },
  {
    label: 'Julia REPL',
    value: 'julia-repl',
    ext: ['jl'],
    icon: 'code_blocks',
  },
  {
    label: 'JSON',
    value: 'json',
    ext: ['json'],
    icon: 'code_blocks',
  },
  {
    label: 'Kotlin',
    value: 'kotlin',
    ext: ['kt', 'kts'],
    icon: 'code_blocks',
  },
  {
    label: 'Lasso',
    value: 'lasso',
    ext: ['lasso', 'ls', 'lasso9'],
    icon: 'code_blocks',
  },
  {
    label: 'LaTeX',
    value: 'latex',
    ext: ['tex', 'latex'],
    icon: 'code_blocks',
  },
  {
    label: 'LDIF',
    value: 'ldif',
    ext: ['ldif'],
    icon: 'code_blocks',
  },
  {
    label: 'Leaf',
    value: 'leaf',
    ext: ['leaf'],
    icon: 'code_blocks',
  },
  {
    label: 'Less',
    value: 'less',
    ext: ['less'],
    icon: 'code_blocks',
  },
  {
    label: 'Lisp',
    value: 'lisp',
    ext: ['lisp', 'lsp', 'cl'],
    icon: 'code_blocks',
  },
  {
    label: 'LiveCode Server',
    value: 'livecodeserver',
    ext: ['lc', 'livecode'],
    icon: 'code_blocks',
  },
  {
    label: 'LiveScript',
    value: 'livescript',
    ext: ['ls'],
    icon: 'code_blocks',
  },
  {
    label: 'LLVM',
    value: 'llvm',
    ext: ['ll', 'bc'],
    icon: 'code_blocks',
  },
  {
    label: 'LSL',
    value: 'lsl',
    ext: ['lsl'],
    icon: 'code_blocks',
  },
  { label: 'Lua', value: 'lua', ext: ['lua'], icon: 'code_blocks' },
  {
    label: 'Makefile',
    value: 'makefile',
    ext: ['make', 'Makefile', 'GNUmakefile'],
    icon: 'code_blocks',
  },
  {
    label: 'Markdown',
    value: 'markdown',
    ext: ['md', 'markdown', 'mdown', 'mkdn'],
    icon: 'code_blocks',
  },
  {
    label: 'Mathematica',
    value: 'mathematica',
    ext: ['nb', 'm', 'wl'],
    icon: 'code_blocks',
  },
  { label: 'MATLAB', value: 'matlab', ext: ['m'], icon: 'code_blocks' },
  {
    label: 'Maxima',
    value: 'maxima',
    ext: ['mac', 'max'],
    icon: 'code_blocks',
  },
  { label: 'MEL', value: 'mel', ext: ['mel'], icon: 'code_blocks' },
  {
    label: 'Mercury',
    value: 'mercury',
    ext: ['m', 'moo'],
    icon: 'code_blocks',
  },
  {
    label: 'MIPS Assembly',
    value: 'mipsasm',
    ext: ['s', 'asm'],
    icon: 'code_blocks',
  },
  { label: 'Mizar', value: 'mizar', ext: ['miz'], icon: 'code_blocks' },
  {
    label: 'Mojolicious',
    value: 'mojolicious',
    ext: ['pl', 'pm'],
    icon: 'code_blocks',
  },
  {
    label: 'Monkey',
    value: 'monkey',
    ext: ['monkey', 'mk'],
    icon: 'code_blocks',
  },
  {
    label: 'MoonScript',
    value: 'moonscript',
    ext: ['moon'],
    icon: 'code_blocks',
  },
  { label: 'N1QL', value: 'n1ql', ext: ['n1ql'], icon: 'code_blocks' },
  {
    label: 'NestedText',
    value: 'nestedtext',
    ext: ['nt'],
    icon: 'code_blocks',
  },
  {
    label: 'Nginx',
    value: 'nginx',
    ext: ['conf', 'nginx'],
    icon: 'code_blocks',
  },
  { label: 'Nim', value: 'nim', ext: ['nim', 'nims'], icon: 'code_blocks' },
  { label: 'Nix', value: 'nix', ext: ['nix'], icon: 'code_blocks' },
  {
    label: 'Node.js REPL',
    value: 'node-repl',
    ext: ['js'],
    icon: 'code_blocks',
  },
  { label: 'NSIS', value: 'nsis', ext: ['nsi', 'nsh'], icon: 'code_blocks' },
  {
    label: 'Objective-C',
    value: 'objectivec',
    ext: ['m', 'mm'],
    icon: 'code_blocks',
  },
  {
    label: 'OCaml',
    value: 'ocaml',
    ext: ['ml', 'mli', 'mll', 'mly'],
    icon: 'code_blocks',
  },
  { label: 'OpenSCAD', value: 'openscad', ext: ['scad'], icon: 'code_blocks' },
  {
    label: 'Oxygene',
    value: 'oxygene',
    ext: ['pas', 'dpr', 'pp'],
    icon: 'code_blocks',
  },
  { label: 'Parser3', value: 'parser3', ext: ['p3'], icon: 'code_blocks' },
  {
    label: 'Perl',
    value: 'perl',
    ext: ['pl', 'pm', 't', 'pod'],
    icon: 'code_blocks',
  },
  { label: 'PF', value: 'pf', ext: ['pf'], icon: 'code_blocks' },
  {
    label: 'PostgreSQL',
    value: 'pgsql',
    ext: ['sql', 'pgsql'],
    icon: 'code_blocks',
  },
  {
    label: 'PHP Template',
    value: 'php-template',
    ext: ['phtml', 'php'],
    icon: 'code_blocks',
  },
  {
    label: 'PHP',
    value: 'php',
    ext: ['php', 'php3', 'php4', 'php5', 'phps', 'phpt'],
    icon: 'code_blocks',
  },
  {
    label: 'Plain Text',
    value: 'plaintext',
    ext: ['txt', 'text', 'md', 'markdown'],
    icon: 'code_blocks',
  },
  { label: 'Pony', value: 'pony', ext: ['pony'], icon: 'code_blocks' },
  {
    label: 'PowerShell',
    value: 'powershell',
    ext: ['ps1', 'psm1', 'psd1'],
    icon: 'code_blocks',
  },
  {
    label: 'Processing',
    value: 'processing',
    ext: ['pde'],
    icon: 'code_blocks',
  },
  {
    label: 'Profile',
    value: 'profile',
    ext: ['profile', 'rc', 'bashrc', 'zshrc'],
    icon: 'code_blocks',
  },
  {
    label: 'Prolog',
    value: 'prolog',
    ext: ['pl', 'pro', 'prolog'],
    icon: 'code_blocks',
  },
  {
    label: 'Properties',
    value: 'properties',
    ext: ['properties', 'ini', 'cfg'],
    icon: 'code_blocks',
  },
  {
    label: 'Protocol Buffers',
    value: 'protobuf',
    ext: ['proto'],
    icon: 'code_blocks',
  },
  { label: 'Puppet', value: 'puppet', ext: ['pp'], icon: 'code_blocks' },
  {
    label: 'PureBasic',
    value: 'purebasic',
    ext: ['pb', 'pbi'],
    icon: 'code_blocks',
  },
  {
    label: 'Python REPL',
    value: 'python-repl',
    ext: ['py'],
    icon: 'code_blocks',
  },
  {
    label: 'Python',
    value: 'python',
    ext: ['py', 'pyw', 'cpy', 'gyp'],
    icon: 'code_blocks',
  },
  { label: 'Q', value: 'q', ext: ['q'], icon: 'code_blocks' },
  { label: 'QML', value: 'qml', ext: ['qml', 'js'], icon: 'code_blocks' },
  {
    label: 'R',
    value: 'r',
    ext: ['r', 'R', 'rmd', 'Rmd'],
    icon: 'code_blocks',
  },
  {
    label: 'ReasonML',
    value: 'reasonml',
    ext: ['re', 'rei'],
    icon: 'code_blocks',
  },
  { label: 'RIB', value: 'rib', ext: ['rib'], icon: 'code_blocks' },
  {
    label: 'Roboconf',
    value: 'roboconf',
    ext: ['graph', 'instances'],
    icon: 'code_blocks',
  },
  {
    label: 'RouterOS',
    value: 'routeros',
    ext: ['rsc', 'txt'],
    icon: 'code_blocks',
  },
  { label: 'RSL', value: 'rsl', ext: ['rsl'], icon: 'code_blocks' },
  {
    label: 'Ruby',
    value: 'ruby',
    ext: ['rb', 'rbw', 'rake', 'gemspec', 'ru'],
    icon: 'code_blocks',
  },
  { label: 'Rust', value: 'rust', ext: ['rs', 'rlib'], icon: 'code_blocks' },
  {
    label: 'Rules Language',
    value: 'ruleslanguage',
    ext: ['rules'],
    icon: 'code_blocks',
  },
  { label: 'SAS', value: 'sas', ext: ['sas'], icon: 'code_blocks' },
  {
    label: 'Scala',
    value: 'scala',
    ext: ['scala', 'sc', 'sbt'],
    icon: 'code_blocks',
  },
  {
    label: 'Scheme',
    value: 'scheme',
    ext: ['scm', 'ss', 'rkt', 'rktd', 'rktl'],
    icon: 'code_blocks',
  },
  {
    label: 'Scilab',
    value: 'scilab',
    ext: ['sci', 'sce'],
    icon: 'code_blocks',
  },
  { label: 'SCSS', value: 'scss', ext: ['scss', 'sass'], icon: 'code_blocks' },
  {
    label: 'Shell',
    value: 'shell',
    ext: ['sh', 'bash', 'zsh', 'ksh', 'csh', 'tcsh'],
    icon: 'code_blocks',
  },
  { label: 'Smali', value: 'smali', ext: ['smali'], icon: 'code_blocks' },
  { label: 'Smalltalk', value: 'smalltalk', ext: ['st'], icon: 'code_blocks' },
  {
    label: 'Standard ML',
    value: 'sml',
    ext: ['sml', 'sig', 'fun'],
    icon: 'code_blocks',
  },
  {
    label: 'SQL',
    value: 'sql',
    ext: ['sql', 'ddl', 'dml'],
    icon: 'code_blocks',
  },
  { label: 'SQF', value: 'sqf', ext: ['sqf'], icon: 'code_blocks' },
  { label: 'Stan', value: 'stan', ext: ['stan'], icon: 'code_blocks' },
  {
    label: 'Stata',
    value: 'stata',
    ext: ['do', 'ado', 'mata'],
    icon: 'code_blocks',
  },
  {
    label: 'Step21',
    value: 'step21',
    ext: ['stp', 'step'],
    icon: 'code_blocks',
  },
  {
    label: 'Stylus',
    value: 'stylus',
    ext: ['styl', 'stylus'],
    icon: 'code_blocks',
  },
  { label: 'Subunit', value: 'subunit', ext: ['subunit'], icon: 'code_blocks' },
  { label: 'SVG', value: 'svg', ext: ['svg'], icon: 'code_blocks' },
  { label: 'Swift', value: 'swift', ext: ['swift'], icon: 'code_blocks' },
  {
    label: 'Tagger Script',
    value: 'taggerscript',
    ext: ['tag'],
    icon: 'code_blocks',
  },
  { label: 'TAP', value: 'tap', ext: ['tap'], icon: 'code_blocks' },
  {
    label: 'Tcl',
    value: 'tcl',
    ext: ['tcl', 'tk', 'itcl', 'itk'],
    icon: 'code_blocks',
  },
  { label: 'Thrift', value: 'thrift', ext: ['thrift'], icon: 'code_blocks' },
  { label: 'TP', value: 'tp', ext: ['tp'], icon: 'code_blocks' },
  { label: 'Twig', value: 'twig', ext: ['twig', 'tpl'], icon: 'code_blocks' },
  {
    label: 'TypeScript',
    value: 'typescript',
    ext: ['ts', 'tsx'],
    icon: 'code_blocks',
  },
  { label: 'Vala', value: 'vala', ext: ['vala', 'vapi'], icon: 'code_blocks' },
  { label: 'VB.NET', value: 'vbnet', ext: ['vb'], icon: 'code_blocks' },
  {
    label: 'VBScript (HTML)',
    value: 'vbscript-html',
    ext: ['html', 'htm', 'asp', 'vbs'],
    icon: 'code_blocks',
  },
  {
    label: 'VBScript',
    value: 'vbscript',
    ext: ['vbs', 'vbe'],
    icon: 'code_blocks',
  },
  {
    label: 'Verilog',
    value: 'verilog',
    ext: ['v', 'vh', 'sv', 'svh'],
    icon: 'code_blocks',
  },
  { label: 'VHDL', value: 'vhdl', ext: ['vhd', 'vhdl'], icon: 'code_blocks' },
  {
    label: 'Vim',
    value: 'vim',
    ext: ['vim', 'vba', 'vbe', 'exrc'],
    icon: 'code_blocks',
  },
  {
    label: 'WebAssembly',
    value: 'wasm',
    ext: ['wasm', 'wat'],
    icon: 'code_blocks',
  },
  { label: 'Wren', value: 'wren', ext: ['wren'], icon: 'code_blocks' },
  {
    label: 'x86 Assembly',
    value: 'x86asm',
    ext: ['asm', 's', 'S'],
    icon: 'code_blocks',
  },
  { label: 'XL', value: 'xl', ext: ['xl', 'xls', 'xlsx'], icon: 'code_blocks' },
  {
    label: 'XML',
    value: 'xml',
    ext: ['xml', 'xsd', 'xsl', 'xslt', 'rss', 'atom', 'svg'],
    icon: 'code_blocks',
  },
  {
    label: 'XQuery',
    value: 'xquery',
    ext: ['xq', 'xquery', 'xql', 'xqm'],
    icon: 'code_blocks',
  },
  { label: 'YAML', value: 'yaml', ext: ['yaml', 'yml'], icon: 'code_blocks' },
  { label: 'Zephir', value: 'zephir', ext: ['zep'], icon: 'code_blocks' },
]
