name: 'ci'
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4 #version is inferred from package.json's packageManager field
        with:
            version: 10.6.2
            run_install: false

      - name: Set node version to 20
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Run build & tsc
        run: pnpm run build
 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 20
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - name: Run unit tests
        run: pnpm run test-ci
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 20
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - name: Lint codebase
        run: pnpm run lint
